install:
  # Install pester via chocolatey
  - cinst pester

version: '0.1.0.{build}'
build: false

test_script:
  - ps: $result = Invoke-Pester -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: |
    (New-Object 'System.Net.WebClient')`
      .UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", `
        (Resolve-Path .\TestsResults.xml))
  - ps: |
    if ($result.FailedCount -gt 0) 
    { 
      throw "$($result.FailedCount) tests failed."
    }
